import type { Celebrity } from '../lib/match';
import json from './celebrities.json';

// Generated by scripts/ingest.mjs from live Wikidata. Cast through unknown to
// avoid TS inferring a 1500-entry literal type for the bundled JSON.
export const CELEBRITIES = json as unknown as Celebrity[];
